### ISSUE TITLE
Feature Req: save credentials to a config file

### ISSUE THREAD

**Issue by ovacikar** [PromyLOPh/pianobar#101]
Its frustrating to manually log on every time I launch pianobar. 
I don't care about password security to listen to music. would be nice to provide credentials via command line or a .pianobar configuration file

**Comment by alexfornuto** [comment]
Having read the man page, I'm still left wondering how one used decrypt_password and encrypt_password to save the password in something other than plaintext.

1. How does one encrypt the password to use it?
2. Is encrypt_password required?

Adding this just to follow the thread trend: There are few things I expect from a man page. Amongst them is a man page that explains options instead of just listing them.

**Comment by PromyLOPh** [comment]
> Having read the man page, I'm still left wondering how one used
> decrypt_password and encrypt_password to save the password in
> something other than plaintext.
You don’t. These settings are completely unrelated to user credentials.
Use password_command instead.

**Comment by alexfornuto** [comment]
> You don’t. These settings are completely unrelated to user credentials.
Use password_command instead.

Which means I first need to create a file containing my encrypted password?

**Comment by PromyLOPh** [comment]
> Which means I first need to create a file containing my encrypted password?
That depends on the password_command you choose. For GPG: Yes.

**Comment by cburmeister** [comment]
![](http://img.michaeljacksonspictures.com/wp-content/uploads/2014/08/popcorn-blank.gif)

**Comment by alexfornuto** [comment]
Nice :smiley:
