### ISSUE TITLE
Using skip causes songs to be -00:40/00:42 with no audio.

### ISSUE THREAD

**Issue by AdamMagaluk** [PromyLOPh/pianobar#301]
As of tonight 2012-09-09 11pm EST iv'e noticed that when using the skip functionality "n" within a station it causes all songs in that station to be 42 seconds long with no audio. Restarting pianobar does not help. However it only effects the station that you skipped in.

I'm guessing its caused by Pandora maybe to block these types of work around programs, any ideas?

**Comment by SevenBits** [comment]
@PromyLOPh Hate to revive this thread, but this happens to me as well, on both the iPad and apps based on pianobar.

**Comment by rmelcer** [comment]
This started happening to me after I signed up for Pandora One (and skipped songs rapidly on a station).

Removing the `#Pandora One` section content from ~/.config/pianobar/config fixed the problem for me. Then, I skipped ~24 songs by switching stations back and forth and was able to reproduce the problem again. Could this have something to do with the partner_user field and/or anything else under the `#Pandora One` section of the config file?

If so, maybe multiple alternative configurations could be added?

CC @PromyLOPh

**Comment by PromyLOPh** [comment]
Well, you can try one of those listed here[1], but if you hit the
rate/skip limit you’ll be back to these 42 seconds of silence. I don’t
think there’s anything I can do, apart from implementing skip limits.

[1] http://6xq.net/playground/pandora-apidoc/json/partners/#partners

**Comment by hgpt** [comment]
Same over here. I've tried a lot of apps on my Mac: Pandorita, PandaBar, Hermes, Piano,... 
After trying so many apps and obtaining the same result, it seems that the problem is an external one, related to Pandora itself, rather than an internal one. Having so many other users complaining over here about the same problem, it's more than enough to convince me that there's nothing wrong with my Mac or the players, but with Pandora.
