### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by mbostwick** [PromyLOPh/pianobar#401]
Would be really nice to have a sleep timer. Seems like an easy feature to add, and helps reduce the upstream usage (which helps pandora, doesn't hurt anyone if users choose to use a sleep timer..no one wins when music is played in an empty room..) .

**Comment by MichaelDimmitt** [comment]
@mbostwick 
https://gist.github.com/MichaelDimmitt/8f0d7680d3f84188fd123e7baa3bc26e

I figured this out today using `timeout`.
```bash
timeout 20m pianobar
```
or
```
timeout 2h pianobar
```

@PromyLOPh , would it make sense to have a usage like this into the readme ?
This is a game changer to my workflow because I can play music until my next meeting. 
Or to train myself to switch tasks.
