### ISSUE TITLE
Pianobar does not work on Raspberry Pi (Debian Wheezy) anymore

### ISSUE THREAD

**Issue by wtellez1** [PromyLOPh/pianobar#451]
It stopped working a while ago, and despite all the efforts re installing it just do not work anymore.

Would it be possible to get an updated tutorial (I am assuming there will be a new version) on how to install it?

**Comment by clarkewd** [comment]
the post from [on here from 11-26-2014, 02:05 AM](http://www.mobileread.com/forums/archive/index.php/t-224800.html) was very helpful - also gives an option for backports to avoid installing ffmpeg from source. note that some libraries need to be installed with `-dev` i.e. `libavcodec-dev` etc.

**Comment by MggMuggins** [comment]
I followed @lanmaster53 's instructions, and I'm hanging on trying to get pianobar to build. I tried without ffmpeg, and got a whole load of errors. Ended up cloning ffmpeg without the history (because it takes up space...), and compiled that sucsessfully, but when I tried to build pianobar, I still end up with the following error:
```Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
    CC  src/main.c
In file included from src/main.c:53:0:
src/main.h:26:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
Makefile:107: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1```

Wondering why this is, and how to fix it.

**Comment by MggMuggins** [comment]
Alright, simple issue of getting the header files for that library. Getting the dev package did the trick. Pianobar compiled just fine, and is running nicely now! :P

**Comment by engineerjoe440** [comment]
I have also followed the instructions as outlined above. I am running into a problem when I run the make command for Pianobar as shown below. Any suggestions?

`pi@raspberrypi:~/pianobar $ make
    CC  src/main.c
In file included from src/main.h:30:0,
                 from src/main.c:53:
src/player.h:37:39: fatal error: libavfilter/avfiltergraph.h: No such file or directory
 #include <libavfilter/avfiltergraph.h>
                                       ^
compilation terminated.
Makefile:107: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1`

From the best of my research, I still cannot find any resources for how to get this resolved, any direction or suggestion is welcome!

**Comment by PromyLOPh** [comment]
Install the development packages for ffmpeg, libav*-dev.

**Comment by engineerjoe440** [comment]
@PromyLOPh 
I've already built ffmpeg on my RPI. What development packages do I need specifically? Thank you!

**Comment by PromyLOPh** [comment]
If you built ffmpeg yourself it should have installed its headers as
well. Did you point PKG_CONFIG_PATH to /<ffmpeg-prefix>/lib/pkgconfig?

**Comment by engineerjoe440** [comment]
To be entirely honest, I'm not sure if I did. I'm pretty new and "green" to most everything with the Raspberry PI...
Is there any way that I can go back and look to tell you one way or the other?

**Comment by PromyLOPh** [comment]
I’m sorry, but I can’t help you with that. Is Debian’s pianobar port
(apt-get install pianobar) not working for you?

**Comment by engineerjoe440** [comment]
[apt-get install pianobar] was what I originally used to install Pianobar, however I've run into the issue now since the latest version available using that command is from 2014, and the current version was dated August, 2017. There are a lot of fixes that I need in the most recent version. Primarily, there's a TLS read error due to Pandora timeouts that has become a recurring nightmare and appears every 3 or 4 songs.
Any suggestions on another resource I might tap? Or another discussion that might have some insight to my problem? Thank you for all of your help!

**Comment by PromyLOPh** [comment]
You must be running a rather old Raspbian/Debian then. Current stable
has a version from 2016, so you might want to look into upgrading your
OS. I can’t point you to any other resources, since compiling from
source is usually considered the last resort (“you know what you’re
doing”).
