### ISSUE TITLE
Playback fails if left paused for a few minutes

### ISSUE THREAD

**Issue by ZevEisenberg** [PromyLOPh/pianobar#463]
I’ve been seeing this since the latest public update (and before, since I was running with `--HEAD` in Homebrew). If I pause pianobar for a few minutes (not that many, probably no more than 5), and then resume playback, the current song plays for a little while, but before it finishes, I get this error:

```
[aac @ 0x7fd172014200] decode_band_types: Input buffer exhausted before END element found
/!\ decode_audio4 (Undefined error: 0)
```

And then it abruptly jumps to the next track.

**Comment by CyborgMaster** [comment]
I'm having the exact same problem.  Pianobar hangs when I pause for more than a couple minutes.  I'm running version 2018.06.22 (which I believe is the latest).  I did follow the trail to #442, but that issue is regarding network connectivity, which I have no problem with and it claims to be fixed on master, but I'm still having the problems pausing.  

Do we know if this is supposed to be resolved, if so, is there anything I can provide to help track down what is going on in my case?

**Comment by PromyLOPh** [comment]
Does pianobar recover if you press Control-C? Is it linked against
ffmpeg or libav?

**Comment by CyborgMaster** [comment]
I'm using the default install from homebrew on macOS, so whatever that one is linked to.  I'm using [control-pianobar](https://github.com/Malabarba/control-pianobar), to run pianobar in headless mode, so I'll run in a console here and see what Control-C does.
