### ISSUE TITLE
Warning: Carbon Component Manager is being deprecated

### ISSUE THREAD

**Issue by mclark4386** [PromyLOPh/pianobar#529]
I've been informed through a CLI birdy that:

    This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

If you need more info or help debugging please let me know!

**Comment by PromyLOPh** [comment]
pianobar is using libao for audio output. Please create an issue at
their bug tracker: https://trac.xiph.org/report/13

**Comment by ZevEisenberg** [comment]
Might want to fix the spelling of the issue name to “deprecated” so others can find it if they search the repo.

**Comment by PromyLOPh** [comment]
Upstream ticket is https://trac.xiph.org/ticket/2210

**Comment by ZevEisenberg** [comment]
It's hard to tell if any progress is being made on https://trac.xiph.org/ticket/2210. Would it be reasonable to redirect the error message in order to suppress it from within Pianobar?

**Comment by PromyLOPh** [comment]
I doubt there’s anything we can do to suppress the message since neither
pianobar nor libao are responsible for printing it.

**Comment by tgjamin** [comment]
Temporary Fix:
`pianobar 2>&1 | grep -v API`
This redirects STDERR on *NIX to STDOUT and then we can grep out the error messages. Unfortunately we lose character echoing when using menus.

**Comment by schwachs** [comment]
pianobar 2>&1 | grep -v API

is awesome. thanks!

**Comment by petracvv** [comment]
You can also just redirect STDERR to /dev/null:
```
pianobar 2>/dev/null
```
Of course, in this case you would lose any legitimate error messages as well but those aren't important unless you are trying to find some problem.

**Comment by seliver** [comment]
thanks @petracvv.

**Comment by has207** [comment]
The fix for libao seems pretty straightforward, there's an example of the changes that need to be made here:

https://github.com/kcat/openal-soft/commit/21c84bcd96a2e457b446e53d3287878e32fc77e0

But AFAICT they're still stuck on svn and submitting diffs through the bug tracker so it seems like kind of a pain to go through the process to submit the change. But if someone's got the time.. :)

**Comment by PromyLOPh** [comment]
> But AFAICT they're still stuck on svn and submitting diffs through the bug tracker so it seems like kind of a pain to go through the process to submit the change. But if someone's got the time.. :)
https://github.com/PromyLOPh/libao – I’ll talk to upstream once the
first change hits this repository.

Your turn.

**Comment by has207** [comment]
https://github.com/PromyLOPh/libao/pull/1

Tag, you're it!

**Comment by has207** [comment]
Btw, this bit in pianobar/Makefile makes it pretty hard to link against the right version when building a custom libao:

ALL_LDFLAGS:=${LDFLAGS} -lpthread -lm \
			${LIBAV_LDFLAGS} ${LIBCURL_LDFLAGS} \
			${LIBGCRYPT_LDFLAGS} ${LIBJSONC_LDFLAGS} \
			${LIBAO_LDFLAGS}

LIBAO_LDFLAGS and friends should precede LDFLAGS (and probably similar for the includes though that's a bit less vital) in order for ld to pick up a custom version rather than the one's that already installed. Then again, maybe there was some pkg-config magic I was supposed to do instead, I just updated the line in the Makefile that defined LIBAO_LDFLAGS to point to my build directory. Just FYI..

**Comment by PromyLOPh** [comment]
> Then again, maybe there was some pkg-config magic I was supposed to do instead,
Set PKG_CONFIG_PATH=/somewhere/libao/lib(64?)/pkgconfig.

**Comment by has207** [comment]
(Sorry for getting offtopic). PKG_CONFIG_PATH doesn't help here, it does set LIBAO_LDFLAGS correctly but the LINK commandline still ends up being:

LINK  pianobar src/main.o src/player.o src/settings.o src/terminal.o src/ui_act.o src/ui.o src/ui_readline.o src/ui_dispatch.o -L. -lpiano  -lpthread -lm -L/opt/local/lib -lavcodec -lavformat -lavutil -lavfilter  -L/opt/local/lib -lcurl  -lgcrypt -L/opt/local/lib -ljson-c  -L/usr/local/ao/lib -lao

So even though -L/usr/local/ao/lib -lao is added at the end system installation is in /opt/local/lib (in this case anyway) so it gets picked up first and linked against rather than the one I'm trying to force. I think you have to redefine ALL_LDFLAGS to add all the custom stuff first then followed by LDFAGS to make sure custom paths take precedence over system defaults.

**Comment by PromyLOPh** [comment]
> So even though -L/usr/local/ao/lib -lao is added at the end system
> installation is in /opt/local/lib (in this case anyway) so it gets
> picked up first and linked against rather than the one I'm trying to
> force.
I see. But afaik there’s no way to tell the linker “use this -L for that
-l only” unless one uses -l/foo/bar/libao.so. pkg-config does not
support that.

> I think you have to redefine ALL_LDFLAGS to add all the custom stuff
> first then followed by LDFAGS to make sure custom paths take
> precedence over system defaults.
Nope, `man ld` says “the directories are searched in the order in which
they are specified on the command line”. Thus LDFLAGS at the beginning
will override pkg-config’s -L.

**Comment by PromyLOPh** [comment]
Fixed upstream, see
https://git.xiph.org/?p=libao.git;a=commit;h=0dc9485462179744d7f1acf319c417a2b3c2a54c
and
https://git.xiph.org/?p=libao.git;a=commit;h=18dc25cd129a7e5a9669cbdd9b076f58063606a2

**Comment by ZevEisenberg** [comment]
Does this mean the fix is going to make its way into pianobar? I just got the latest update from homebrew, but it's still giving me this warning.

**Comment by PromyLOPh** [comment]
You can ask the person maintaining libao’s homebrew port to apply these
patches.

**Comment by ZevEisenberg** [comment]
[Done](https://twitter.com/ZevEisenberg/status/701798701921075200). Thanks for the suggestion.

**Comment by triplepoint** [comment]
If anyone wants to get your hands dirty on this, I got the updated libao code installing with a modified homebrew "formula" for libao, and I can verify that pianobar stopped giving the Carbon warnings.  

Given that libao hasn't cut an official versioned release, I doubt that homebrew would want to bump their official libao release to some random commit - but in any event, I got it working locally, and so far so good.

Here's what I did:

Modify `/usr/local/Library/Formula/libao.rb` to have this content:
```
class Libao < Formula
  desc "Cross-platform Audio Library"
  homepage "https://www.xiph.org/ao/"

  ## Original libao source
  #url "http://downloads.xiph.org/releases/ao/libao-1.2.0.tar.gz"
  #sha256 "03ad231ad1f9d64b52474392d63c31197b0bc7bd416e58b1c10a329a5ed89caf"

  # More recent libao commit:
  # https://git.xiph.org/?p=libao.git;a=commit;h=18dc25cd129a7e5a9669cbdd9b076f58063606a2
  # We'll call it "1.2.0-snapshot-18dc25c" to indicate that it's a bit ahead of 1.2.0 proper.
  url "https://git.xiph.org/?p=libao.git;a=snapshot;h=18dc25cd129a7e5a9669cbdd9b076f58063606a2;sf=tgz"
  sha256 "c4a1c2caac8dff249003338e20df2b614cf59e9f5c3b33c663ef8b627a370062"
  version "1.2.0-snapshot-18dc25c"

  bottle do
    revision 1
    sha256 "159aa7704f0a3cd36bfdf659ca8ec9c399077274bff1b68aa0497fdda8b6da44" => :el_capitan
    sha256 "08d568c4bed498b2920983d9b848213779164c15489c82cc61429533337d19f5" => :yosemite
    sha256 "81b1d6c5d1920092fba0470db2840414eb99bba8ec63d6d22800e79090db8e4b" => :mavericks
    sha256 "21aa15e92c5577a4a610de8fbb3f5a72638a0c37a40c4ebebc14826359932efa" => :mountain_lion
  end

  depends_on "pkg-config" => :build

  # Building from an between-releases source also requires automake, autoconf, and libtool
  # in order to be able to run autogen.sh
  depends_on "automake" => :build
  depends_on "autoconf" => :build
  depends_on "libtool" => :build

  def install
    # Add autogen.sh - I believe this must be run as part of libao's release process, since
    # the files generated here were already present in the 1.2.0 proper release tarball.
    system "AUTOMAKE_FLAGS=--include-deps ./autogen.sh"
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}",
                          "--enable-static"
    system "make", "install"
  end
end
```
I added some comments to hopefully explain the changes I made.

You can then uninstall and reinstall libao with:
```
brew remove libao
brew install libao
```

If this screws up for you and you need to return to the previous behavior, you can do:
```
brew remove libao
rm /usr/local/Library/Formula/libao.rb
brew update
brew update 
brew instal libao
```

And that should get you back to the official 1.2.0 release.

Good luck.

**Comment by whirlyNerd** [comment]
@triplepoint - Worked like a champ. Thanks!

**Comment by alexfornuto** [comment]
@triplepoint You're the hero this city needs. Thanks!

**Comment by ZevEisenberg** [comment]
Does this mean it's fixed in Pianobar, or only if we do the procedure outlined by @triplepoint at https://github.com/PromyLOPh/pianobar/issues/529#issuecomment-192764161?

**Comment by PromyLOPh** [comment]
The latter. It has been fixed in libao and now package maintainers have
to pick up the patch.

**Comment by rdj** [comment]
Yay been waiting for this fix for a long time. Instead of the url thing @triplepoint suggested, you could instead just add a head line: 
```
head "https://git.xiph.org/libao.git"
```

That way you don't need the sha hash or to give it a version number or any of that. You'd install with `brew install --HEAD libao`. And brew will probably be less confused, since it knows all about building from HEAD. Might be worth sending a PR to homebrew with the head line since that is a lot more likely to be accepted than changing the default package to a non-official release.

**Comment by rdj** [comment]
Followed my own advice: https://github.com/Homebrew/homebrew-core/pull/912

**Comment by Behinder** [comment]
Well I have still the warning after the year. Using MacPorts not homebrew. Latest libao.
What to do?

**Comment by PromyLOPh** [comment]
Since it’s an issue with MacPorts you’ll have to open a ticket
here: https://guide.macports.org/#project.tickets
