### ISSUE TITLE
songfinish eventcmd fields are NULL when switching stations

### ISSUE THREAD

**Issue by reillysiemens** [PromyLOPh/pianobar#584]
My C fu is a little weak, so unfortunately I haven't been able to tie down the exact lines in `pianobar` that cause this. I've been working with the _wonderful_ eventcmd feature and it appears as though a `songfinish` is triggered when switching stations, but fields like `artist`, `album`, `coverArt`, etc. are nullified before the event is actually triggered. This means that if I'm trying to capture listening data for historical purposes I lose relevant data every time I switch stations. This isn't a huge deal as I don't do that terribly frequently, but it'd be nice to know if this is intended behavior or if I'm crazy.

Interestingly, other fields like `songDuration`, `songPlayed`, and `stationName` still retain some value. I wonder if something inside [`BarUiStartEventCmd`](https://github.com/PromyLOPh/pianobar/blob/master/src/ui.c#L767) is causing this behavior.

**Comment by PromyLOPh** [comment]
BarUiActSelectStation in ui_act.c destroys the current playlist
(app->playlist), signaling BarMainLoop from main.c to fetch a new
playlist. Unfortunately its first item is the *current* song, which
would be required to correctly fill in song information in
BarMainPlayerCleanup (main.c).

> Interestingly, other fields like `songDuration`, `songPlayed`, and
> `stationName` still retain some value.
Duration and played are stored in the player’s context and should be
correct. stationName will be the *new* station’s name, because
curStation is changed as well.

I’ve got a patch ready, which I am going to commit in a few days (if it
works): https://gist.github.com/09fd53a4f67f4acaaef61a66e195deb9
Unfortunately we cannot return the correct station name for deleted
stations (i.e. delete current station, songfinish returns no station
name). That would require garbage collection/refcounting.

**Comment by reillysiemens** [comment]
Thanks for taking a look at that, @PromyLOPh!
