### ISSUE TITLE
Program stops responding after about 10 minutes of running

### ISSUE THREAD

**Issue by EthanZeigler** [PromyLOPh/pianobar#610]
After about 10 or 15 minutes of use, pianobar stops responding entirely. No error output, the time marker stops, and sound output stops. After leaving the program alone for a few minutes after this freeze, it goes back to the station selection menu. Trying to select a station throws an internal error. I tried to find a log file of the error with no luck.

Using the newest pianobar version on homebrew with OSX 10.11.6.

**Comment by PromyLOPh** [comment]
Is this still a problem? “sound output stops” and “internal error”
sounds alot like an issue on Pandora’s end. Hint: You can interrupt
playback by pressing Control-C (^C) or sending SIGINT.

**Comment by EthanZeigler** [comment]
Interestingly enough, Control C has no effect when this starts. I forgot to mention that.

**Comment by PromyLOPh** [comment]
Is pulseaudio installed?

**Comment by EthanZeigler** [comment]
No, it isn't. I have nothing special installed with it. I just used brew install pianobar. I've also getting some static during playback too, but as I read around, that probably isn't pianobar's fault.

**Comment by Cightline** [comment]
I have the same problem, let me know if there is anything I can do.

**Comment by PromyLOPh** [comment]
I remember seeing similar issues, but I can’t find them right now. #503
and #498 look similar as well.

Can you please tell me: Your OS, ffmpeg version and pianobar version. A
gdb backtrace would be very nice.
https://wiki.ubuntu.com/Backtrace#Generation expains how to do that, but
make sure to run `handle SIGINT nostop noprint pass` before `run`. The
output contains your password and auth token. Please don’t post those in
public (i.e. remove them or send me the backtrace in private).

@EthanZeigler: That error usually occurs when the connection is
interrupted. So it could be a connectivity issue that pianobar (or
ffmpeg?) is unable to recover from.

**Comment by Cightline** [comment]
I've been unable to reproduce this now. Maybe its something on Pandora's side (they have been updating their website).

**Comment by RichiH** [comment]
This seems to be a race condition.

I can reliably make pianobar hang within 0-15 minutes by simply listening to music, doing nothing else.

Running within gdb, I am unable to reproduce a single hang after countless hours of always-on listening, even leaving the stream run over night.

**Comment by NECooley** [comment]
Same issue here. Precisely as described.  After about 10-15 minutes playback freezes, ctrl-C does not always work, changing stations results in an unwritten error.  I tried running w/ sudo and the freeze happened after 30 seconds rather than ten minutes. I do, however, have pulseaudio running; the other fixes associated with pulse have not worked for me.

Requested Information:
OS: Linux <hostname> 4.11.0-13-generic #19~16.04.1-Ubuntu SMP Wed Aug 2 20:06:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux Mint 18.2 Sonya

ffmpeg: amd64/xenial-security 7:2.8.11-0ubuntu0.16.04.1 uptodate (I don't recall this being a dependency for pianobar, does it use this?)

pianobar: amd64/xenial 2015.11.22-1 uptodate

gdb output: https://pastebin.com/HL5G3PU2

**Comment by PromyLOPh** [comment]
Yes, ffmpeg has been a dependency for quite a while now. Since
pulseaudio is involved you’re on your own. Sorry.

**Comment by jalada** [comment]
Woah, blast from the past
