### ISSUE TITLE
Compile-time error, AVCodecParameters

### ISSUE THREAD

**Issue by glyndon** [PromyLOPh/pianobar#614]
under the latest code,  previous versions of which compiled without problem, now I get a series of errors beginning with: 

src/player.c:175:8: error: unknown type name ‘AVCodecParameters’

Did I perhaps miss a necessary library/header update notification?
(Raspbian 8)

**Comment by PromyLOPh** [comment]
Yep, I had a few minutes and replaced a deprecated ffmpeg API in commit
f3dff6792232d1e3f2deb8baf21dc1fa81581090. Its replacement is rather new
and requires libav>=12 or ffmpeg>=3.1. Both are (probably) not available
in the “stable” branch of your favorite Linux distribution yet. Since
there are no functional changes (nor improvements) you can safely revert
that commit or just use release 2016.06.02.

**Comment by glyndon** [comment]
reverting succeeds. Thank you.
