### ISSUE TITLE
Get stations... Error: Invalid response.

### ISSUE THREAD

**Issue by tmccisdj** [PromyLOPh/pianobar#619]
I am on fedora 25 and I just pulled pianobar (from master) and built it, after adding my account info to the config file I get this error.

pianobar
Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.
(i) Login... Ok.
(i) Get stations... Error: Invalid response.

**Comment by PromyLOPh** [comment]
I assume this is caused by commit
43153057c66f4cf1ed6a97671e9aa59e0eacb3bd.

Can you apply this patch
https://gist.github.com/ecd8a4d281e998347ed7c9e804749dca and post the
line starting with “(i) Get stations...”, please? Something in your
station response must be different from what I receive, because it works
for me.

**Comment by tmccisdj** [comment]
ok so I read the output and pandora was being blocked, I didn't think this was an issue at first because it said the login succeeded but that was my issue. I'm sure its a big task but I could see that verbose output being useful for users debugging without having to post an issue if you added a -v option when running the code. Thank you for your quick reply and helping me solve the issue.

**Comment by PromyLOPh** [comment]
> ok so I read the output and pandora was being blocked
…by a local firewall?

> I'm sure its a big task but I could see that verbose output being
> useful for users debugging without having to post an issue if you
> added a -v option when running the code.
Actually that’s been on my todo list for ages now.
