### ISSUE TITLE
Feature: Unlove / Unban

### ISSUE THREAD

**Issue by mythmon** [PromyLOPh/pianobar#73]
It would be nice to unlove or unban a son, either when it is playing or from the history menu.

This would be especially useful to undo the damage when I mash the minus key a few times thinking it is a volume key :).

**Comment by justinmayer** [comment]
I just banned several songs by mistake and wanted to undo those actions, but I could not figure out how to do so. For anyone else trying to do the same, hit `=` and then `f`, and then choose the number corresponding to songs marked `</3` (which is the ban symbol apparently).

**Comment by MichaelDimmitt** [comment]
@justinmayer late in responding to your post.
I figured it out just now because I just figured it out for myself right now. 

what you need to do. 
(has to be recent [within previous 4 songs.])
1) in pianobar type ```?``` -- to get help settings.
2) type ```h``` -- "song history"
3) select the song by typing number ```1-4```. and press ```enter```
4) "what do you want to do with this song" type ```?``` to see options.
5) I switched from having banned the song to loving the song by typing ```+```
